### ISSUE TITLE
[deploy]CI 构建

### ISSUE THREAD

**Issue by LoeiFy** [acyortjs/acyortjs.github.io#32]
通过 GitHub webhooks 和 CircleCI 的支持，你的网站能够自动构建在你完成写作之后

当设置好自动构建之后，更新网站只需要一个浏览器新增一个 issue 即可

**如何工作**

以下是构建流程图，这里还有一个例子项目： [repository](https://github.com/LoeiFy/Recordum/)

![ci](https://user-images.githubusercontent.com/2193211/35319242-eebaa61a-0119-11e8-87ee-339d984d4f05.png)

**如何设置**

## 主要步骤

**再次说明，整个设置过程并不需要本地环境，全程网页操作即可**

* 一个 CircleCI API token
* 一个 GitHub 项目
* 两个 GitHub access tokens
* 配置 CircleCI
* 配置 Github 项目

### CircleCI Token

通过 GitHub 登录 [CircleCI](https://circleci.com)，获取 CircleCI [token](https://circleci.com/account/api)，命名为 `ci-token`

> 请注意 CircleCI 会获取你的项目所有权限，包括私有项目 

### GitHub Tokens

登录 GitHub，在 access  [token](https://github.com/settings/tokens) 页面，创建两个 tokens:

* 不需要任何权限，命名为 `read-token`
* 只需要 `public_repo` 权限，命名为 `repo-token`

### GitHub 项目

这个项目需要两个分支

**master 分支** 

CircleCI 和 AcyOrt 配置文件放到这个分支. 文件结构如下:

```
.
├─ .circleci
├  └─ config.yml
└─ config.yml
```

```yml
# .circleci/config.yml
version: 2
jobs:
  build:
    docker:
      - image: node:latest
      
    working_directory: ~/acyort
    
    branches:
      only:
        - master # config branch

    steps:
      - checkout
      - run: npm install acyort -g
      - run: acyort init 
      - run: cp config.bak.yml config.yml 
      - run: npm i # 可选，如果你需要安装 npm 插件
      - run: acyort build  
      - run: git checkout .  
      - run: git checkout gh-pages # 静态文件存放分支
      - run: git reset --hard origin/gh-pages
      - run: cp -R public/* . 
      - run: rm config.bak.yml 
      - run: rm -R scripts themes public 
      - run: git add .
      - run: git config user.name "username" # 你的 GitHub 用户名
      - run: git config user.email "email" # 你的 GitHub 邮箱
      - run: git commit -m "Updated by circleci - `date`"
      # 下面填写你的 usename 和 repository  
      - run: git push -q https://${gh_token}@github.com/username/repository.git gh-pages:gh-pages 
```

> 你可以设置 git commit 时区

```
run: git commit -m "Updated by CircleCI - `TZ='Asia/Shanghai' date`"
```

---

```yml
# config.yml
# 只显示重要设置项

user:  # 你的 GitHub username
repository:  # 你的 GitHub repository

public_dir: public # 重要，跟 CircleCi 配置相同: public
timezone:  # 设置你的时区
token:  # 你的`read-token`
```

**gh-pages 分支** 

**必须** 存在。 生成的静态文件会存放到这个分支。

如果有 CNAME 文件也放到这里

这里也应该添加一个 `.gitignore` 文件

```
Thumbs.db
.DS_Store
_issues.json
node_modules/
public/
```

### CircleCI 配置

登录 CircleCI，点击 PROJECTS，添加上面的那个项目，选择 platform 为 `Linux & Node`，然后点击 Start building。（首次会失败，因为没有 token）

* 添加 Environment variables，字段名: `gh_token` 值: 你获得的 `repo-token`
* 在 Advanced settings，设置 `Github Status updates` 以及 `Build forked pull requests` off

### Repository 设置

登录 GiHub, 在 repository settings 页面，添加 webhooks

**设置 Payload URL**

CircleCI 的出发构建 API 为：`/project/:vas-type/:username/:project/tree/:branch`。所有 webhook s 的
 URL 应该这样：`https://circleci.com/api/v1.1/project/github/username/repository/tree/master?circle-token=ci-token`

- `username`: 你的 GitHub username
- `repository`: 你的 GitHub repository
-  `ci-token`: 你获得的 `ci-token`

**设置 Content type**

使用 `application/json`

**设置 Trigger events** 

在 `Let me select individual events`，只需要点 `Issues` 

## 最后

轻松的在 issues 上写你的网站
